#∑˛ŒÒ≈‰÷√
server:
  host: localhost
  port: 8080

#Spring≈‰÷√
spring:
  application:
    name: eureka-zuul-hystrix

#Eureka≈‰÷√
eureka:
  instance:
    hostname: localhost
    instance-id: ${server.host}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #,http://localhost:8762/eureka

#Actuator≈‰÷√
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

#Zuul≈‰÷√
zuul:
  routes:
    eureka-client: /api/**

#»’÷æ≈‰÷√
logging:
  level:
    root: error
    com.cn.web: debug