#Server
server:
  host: localhost
  port: 8083

#Spring
spring:
  #application
  application:
    name: uaa_oauth2

  #datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uaa_oauth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: admin
    time-between-eviction-runs-millis: 3600000

  #JPA
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create

#Actuator
management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

#S4j
logging:
  level:
    root: error
    com.cn.web: debug